In [1]:
#Load data 
import pandas as pd 
import numpy as np 
news_df = pd.read_csv("news.csv",sep=",")

#Preprocess data 
import string 
news_df['CATEGORY'] = news_df.CATEGORY.map({ 'b': 1, 't': 2, 'e': 3, 'm': 4 }) 
#news_df['TITLE'] = news_df.TITLE.map(str.maketrans('','', string.punctuation))
news_df= news_df.replace(np.nan, '', regex=True) 
news_df.tail(6)

#Split into train and test data sets 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(news_df['TITLE'],news_df['CATEGORY'],random_state = 1) 
print("Training dataset: ", X_train.shape[0]) 
print("Test dataset: ", X_test.shape[0])

#Extract features 
from sklearn.feature_extraction.text import CountVectorizer

count_vector = CountVectorizer(stop_words = "english") 
training_data = count_vector.fit_transform(X_train) 
testing_data = count_vector.transform(X_test)

#Train Multinomial Naive Bayes classifier 
from sklearn.naive_bayes import MultinomialNB

naive_bayes = MultinomialNB() 
naive_bayes.fit(training_data, y_train)

#Generate predictions 
predictions = naive_bayes.predict(testing_data)
predictions

from sklearn.metrics import accuracy_score 
print("Accuracy:", accuracy_score(y_test, predictions))

from sklearn.metrics import classification_report 
print(classification_report(y_test, predictions))

from sklearn.metrics import confusion_matrix 
print("confusion matrix is \n", confusion_matrix(y_test,predictions))

Training dataset:  316814
Test dataset:  105605
Accuracy: 0.9283367264807537
              precision    recall  f1-score   support

           1       0.91      0.91      0.91     29028
           2       0.90      0.91      0.90     27174
           3       0.97      0.96      0.96     38082
           4       0.92      0.92      0.92     11321

    accuracy                           0.93    105605
   macro avg       0.92      0.92      0.92    105605
weighted avg       0.93      0.93      0.93    105605

confusion matrix is 
 [[26306  1842   478   402]
 [ 1733 24703   496   242]
 [  547   717 36607   211]
 [  389   187   324 10421]]
